### ISSUE TITLE
filter api endpoint in config 

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/nova-operator#156]
nova-api should have
[DEFAULT]
enabled_apis=['osapi_compute']

and the metadtat confg should have

[DEFAULT]
enabled_apis=['metadata']

**Comment by gibizer** [comment]
This was already fixed by https://github.com/openstack-k8s-operators/nova-operator/commit/359004c3763cd474cf2de2e419ba3f50b82d9b2f

https://github.com/openstack-k8s-operators/nova-operator/blob/f07662231bdb7d4ea77710d192ae1483b03ee417/templates/nova.conf#L32-L40
