### ISSUE TITLE
api should be useing new default

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/nova-operator#157]
enforce_new_defaults shoudl be set to true for the api

**Comment by gibizer** [comment]
OK this is still valid, we did not enable the new policy defaults https://github.com/openstack-k8s-operators/nova-operator/blob/main/templates/nova.conf#L59

**Comment by SeanMooney** [comment]
fix by https://github.com/openstack-k8s-operators/nova-operator/pull/627
