### ISSUE TITLE
Support cell deletion

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#172]
When an entry is removed from Nova.cellTemplates map the nova-controller does not delete the corresponding NovaCell CR today. But it should.

**Comment by auniyal61** [comment]
Here when operator wants to delete a cell, how they should/will proceed?
1. delete cell from nova using nova-mange cmd
2. update nova controlpalne, to remove entry of cell.

OR

1. update nova controlpalne, to remove entry of cell.
2. and nova-mange call will be automated from nova-operator

**Comment by gibizer** [comment]
This is tracked in https://issues.redhat.com/browse/OSPRH-105
