### ISSUE TITLE
ExternalCompute controller re-runs the ansible deplyoment steps after each nova-operator restart

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#294]
It seems the current reconciler re-runs the deployment steps after each nova-operator restart.
To reproduce:
1. create NovaExternalCompute and wait until it becomes ready after it run the ansible deploy steps
2. delete the nova-operator-controller-manager pod to trigger a restart of nova-operator

Expected behavior:
If nothing is changed in the NovaExternalCompute resource then the ansible code is not re-run

Actual behavior:
The ansible code is re-run each time.

While re-running ansible should not cause any trouble as we expect that the ansible code is idempotent it will still causes many 2N ansible execution in an environment with N compute for each nova-operator restart.

**Comment by SeanMooney** [comment]
yep this is something i was aware of.
for the initial pr i kept this the same as all the other reconsile loop which also rerun on operator restart.

but i agree we should special case this in a follow up.

**Comment by gibizer** [comment]
This is targeting NovaExternalCompute but that is unused now and will be deleted by https://github.com/openstack-k8s-operators/nova-operator/pull/476
