### ISSUE TITLE
Failed AnsibleEE CRs should be deleted before retrying

### ISSUE THREAD

**Issue by kk7ds** [openstack-k8s-operators/nova-operator#296]
A failed ansible run leaves the job and ansibleee CRs in place for forensic reasons. However, even deleting the NovaExternalCompute will cause those to not be re-created on the next run, leading to confusion about why changes are not being taken into account.

Any time we're going to do an ansible run, we should delete/recreate/update a previous failed ansibleee CR so that new changes to any of the inputs are used for the subsequent job.

**Comment by bogdando** [comment]
* NovaExternalCompute does no own the Ansibleee CR it creates and therefore when NovaExternalCompute is deleted the rest of the tree remains

**Comment by bogdando** [comment]
this whole thing looks like is going to be addressed as the point 2 in https://github.com/openstack-k8s-operators/nova-operator/issues/319

**Comment by SeanMooney** [comment]
yep that was the plan

**Comment by SeanMooney** [comment]
this was not actully adressed by #387 although it is related.

**Comment by bogdando** [comment]
Related https://github.com/openstack-k8s-operators/nova-operator/issues/319

**Comment by gibizer** [comment]
This is targeting NovaExternalCompute but that is unused and will be deleted by https://github.com/openstack-k8s-operators/nova-operator/pull/476
