### ISSUE TITLE
support multiple ceph users per cluster

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/nova-operator#315]
basically i just need to change the cluster user map form a map of string to string to a map of string to list of string and add an additional loop over the users

_Originally posted by @SeanMooney in https://github.com/openstack-k8s-operators/nova-operator/issues/301#issuecomment-1486669110_

**Comment by SeanMooney** [comment]
PR: #301  adds support for basic ceph integration including support for multiple ceph clusters but it does not currently support multiple users per cluster.

that is a trivial thing to fix but we need to actually test it so this tracks closing that gap.

**Comment by gibizer** [comment]
This is targeting NovaExternalCompute but that is unused now and will be deleted in https://github.com/openstack-k8s-operators/nova-operator/pull/476
