### ISSUE TITLE
Ansible compute followup TODOs

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#319]
TODOs left for followup:
* do not requeu while waiting for the ansible jobs
* add controller ref to the ansible jobs we create to not leak them if nova is deleted while the job running
* pass NetworkAttachments to the ansiblee CR
* create a common ensureAEEDeploy function from the two similar one
* blank out nova-compute.conf
* add envtest coverage to the negative ansible execution case.

_Originally posted by @gibizer in https://github.com/openstack-k8s-operators/nova-operator/pull/268#pullrequestreview-1344058191_

**Comment by bogdando** [comment]
* NovaExternalCompute does no own the Ansibleee CR it creates and therefore when NovaExternalCompute is deleted the rest of the tree remains

**Comment by gibizer** [comment]
This issue is targeting NovaExternalCompute but that is unused now and will be deleted by https://github.com/openstack-k8s-operators/nova-operator/pull/476
