### ISSUE TITLE
Disable periodic host discovery in nova-scheduler

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#487]
The periodic host discovery does not scale as it generates DB load by periodically scanning the cell DBs for new hosts. Instead host discovery is expected to be triggered to after new hosts are added to a cell. Right now nova-operator cannot detect that so this is up to the user / dataplane-operator to trigger the host discovery.

**Comment by SeanMooney** [comment]
we shoudl proably put the make target in the nova repo not install yamls

**Comment by SeanMooney** [comment]
with that said for ci i think just adding a step the the zuul playbook to invoke it is also fine.

the ci jobs can trivially do  oc rsh nova-cell1-conductor-0 nova-manage cell_v2 discover_hosts

**Comment by gibizer** [comment]
> we shoudl proably put the make target in the nova repo not install yamls

Putting the make target to nova-operator repo will not work for CI jobs using install_yamls to deploy. But if we can also ignore the make target thing and just add fixes to the CI jobs to run oc commands.
