### ISSUE TITLE
Race condition in functional test: Nova reconfiguration [It] reconfigures nova-metadata service if metadata shared secret is changed

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#634]
I saw multiple times that `Nova reconfiguration [It] reconfigures nova-metadata service if metadata shared secret is changed` fais randomly on the gate. Probably a race condition. 

Example failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/633/pull-ci-openstack-k8s-operators-nova-operator-main-functional/1736720180576260096

**Comment by mrkisaolamb** [comment]
I run this tests 50 times and didn't saw this issue, maybe we can close it? WDYT @gibizer 
```
Ran 19 of 323 Specs in 35.317 seconds
SUCCESS! -- 19 Passed | 0 Failed | 0 Pending | 304 Skipped

coverage: 68.7% of statements

All tests passed...
Will keep running them until they fail.
This was attempt #50

```
