### ISSUE TITLE
[envtest]Make timeout configurable

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#77]
When envtest runs agains an existing cluster it can be slower than with running locally, so test timeouts needs to come from ENV variables.

**Comment by gibizer** [comment]
Note that lib-common improvement for configurability is proposed here https://github.com/openstack-k8s-operators/lib-common/pull/68 Some configurability can already been done for Job and Deployment, but not for DB creation.

**Comment by mrkisaolamb** [comment]
@gibizer can we close this issue? AFAIK currently timeouts are configurable inside of each operator and that sounds like correct behaviour because we can easly spot that something is slower now or make test db slower

**Comment by gibizer** [comment]
Yeah most of the requeue timeout is no parameters in the lib-common functions and where it isn't nova-operator simply ignores the requeue request from lib-common if the nova-operator is watching the resource. So I agree that this can be closed.
